### ISSUE TITLE
Add CI (Travis/AppVeyor/etc)

### ISSUE THREAD

**Issue by XVilka** [sashs/Ropper#104]
To check if it works or not

See the basic template here: https://docs.travis-ci.com/user/languages/python/

It makes sense to add also the flake8 checks:
```yaml
install:
    - pip install --upgrade pip
    - pip install flake8

before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

```
